# Copyright (c) Jupyter Accessibility Development Team.
# Distributed under the terms of the Modified BSD License.

name: a11y-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9.*
  # for base a11y testing
  - nodejs=16.*
  - jupyterlab=3.*
  # for the notebook example
  - ipython
  - ipywidgets
  - matplotlib
  - numpy
  - scipy
