# Copyright (c) Jupyter Accessibility Development Team.
# Distributed under the terms of the Modified BSD License.

image: quansight/jupyter-a11y:latest

tasks:
  - name: Install JupyterLab Node.js testing dependencies
    init: |
      cd testing/jupyterlab
      echo " 📦 Installing node dependencies "
      yarn install
      npx playwright install
      echo "🚀 Dependencies installed "
      cd /workspace/accessibility/

# --------------------------------------------------------
# exposing ports
ports:
  - port: 9323
  - port: 8888

# some useful extensions to have
vscode:
  extensions:
    - eamodio.gitlens
    - ms-python.python
    - yzhang.markdown-all-in-one
    - bungcip.better-toml

# --------------------------------------------------------
# using prebuilds for the container
# With this configuration the prebuild will happen on push to master
github:
  prebuilds:
    # enable for main/default branch
    master: true
    # enable for other branches (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    # need to change
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    # need to change
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
