name: Setup and build JupyterLab
description: |
  Install and build concrete versions of JupyterLab from source
  for a11y testing purposes
inputs:
  repository:
    description: JupyterLab repository, for example jupyterlab/jupyterlab
  ref:
    description: The Jupyterlab repository's branch, tag, or SHA to checkout.

runs:
  using: composite
  steps:
    - name: Checkout JupyterLab 🛎
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository || 'jupyterlab/jupyterlab' }}
        ref: ${{ inputs.ref || 'main' }}
        path: jupyterlab

    - name: Build JupyterLab 🏗
      run: |
        echo "::group:: Building JupyterLab 🏗"
        conda run --prefix $CONDA_PREFIX ./scripts/ci_install.sh
        conda run --prefix $CONDA_PREFIX jlpm run build
        echo "::endgroup::"
        which jupyter
        jupyter lab --version
      shell: bash -l {0}
      working-directory: jupyterlab
